AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an Application Load Balancer with Target Group for Neptune Cluster

Parameters:
  VpcId:
    Type: String
    Description: VPC of Neptune
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the ALB (must be in different Availability Zones)
  CertArn:
    Type: String
    Description: ARN of the SSL certificate
  TargetIP:
    Type: String
    Description: Private IP of the Neptune instance
  HostedZoneId:
    Type: String
    Description: Hosted Zone ID for powerodd.com

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ApplicationLoadBalancer
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroup
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Type: application

  NeptuneTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: NeptuneTargetGroup
      Port: 8182
      Protocol: HTTPS
      VpcId: !Ref VpcId
      HealthCheckProtocol: HTTPS
      HealthCheckPort: 8182
      HealthCheckPath: /status
      TargetType: ip
      Targets:
        - Id: !Ref TargetIP

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NeptuneTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 8182
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: !Ref CertArn

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: neptune-db.powerodd.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: false

Outputs:
  LoadBalancerDNSName:
    Description: The DNS name of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
