AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS CloudFormation template describing your function.

Resources:
  LambdaExecutionRoleWithVpc:
    Type: AWS::IAM::Role
    Condition: AddVpc
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies: 
        - PolicyName: "LambdaPolicyWithVpc"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "ec2:DescribeInstances"
                  - "ec2:CreateNetworkInterface"
                  - "ec2:AttachNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DeleteNetworkInterface"
                  - "rds:*"
                  - "neptune-db:*"
                  - "kms:ListAliases"
                  - "kms:ListKeyPolicies"
                  - "kms:ListKeys"
                  - "kms:ListRetirableGrants"
                  - "logs:DescribeLogStreams"
                  - "logs:GetLogEvents"
                  - "sns:ListSubscriptions"
                  - "sns:ListTopics"
                  - "sns:Publish"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:ListStackResources"
                  - "cloudwatch:ListMetrics"
                  - "cloudwatch:GetMetricData"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "iam:GetPolicy"
                  - "iam:GetPolicyVersion"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListRoles"
                  - "lambda:*"
                  - "logs:DescribeLogGroups"
                  - "states:DescribeStateMachine"
                  - "states:ListStateMachines"
                  - "tag:GetResources"
                  - "xray:GetTraceSummaries"
                  - "xray:BatchGetTraces"
                  - "iam:PassRole"
                  - "logs:FilterLogEvents"
                Resource: "*"
              - Effect: "Allow"
                Action: 
                  - "iam:PassRole"
                Resource: "*"
                Condition: 
                  StringEquals: 
                    iam:PassedToService: 
                      - "lambda.amazonaws.com"
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                Resource: "arn:aws:logs:ap-southeast-2:337393854581:*"
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - "arn:aws:logs:ap-southeast-2:337393854581:log-group:*"

  LambdaExecutionRoleWithoutVpc:
    Type: AWS::IAM::Role
    Condition: NoVpc
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies: 
        - PolicyName: "LambdaPolicyWithoutVpc"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "kms:ListAliases"
                  - "kms:ListKeyPolicies"
                  - "kms:ListKeys"
                  - "kms:ListRetirableGrants"
                  - "logs:DescribeLogStreams"
                  - "logs:GetLogEvents"
                  - "sns:ListSubscriptions"
                  - "sns:ListTopics"
                  - "sns:Publish"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:ListStackResources"
                  - "cloudwatch:ListMetrics"
                  - "cloudwatch:GetMetricData"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "iam:GetPolicy"
                  - "iam:GetPolicyVersion"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListRoles"
                  - "lambda:*"
                  - "logs:DescribeLogGroups"
                  - "states:DescribeStateMachine"
                  - "states:ListStateMachines"
                  - "tag:GetResources"
                  - "xray:GetTraceSummaries"
                  - "xray:BatchGetTraces"
                  - "iam:PassRole"
                  - "logs:FilterLogEvents"
                Resource: "*"
              - Effect: "Allow"
                Action: 
                  - "iam:PassRole"
                Resource: "*"
                Condition: 
                  StringEquals: 
                    iam:PassedToService: 
                      - "lambda.amazonaws.com"
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                Resource: "arn:aws:logs:ap-southeast-2:337393854581:*"
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - "arn:aws:logs:ap-southeast-2:337393854581:log-group:*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
      Description: ''
      MemorySize: 128
      Timeout: 30 
      FunctionName: !Ref FunctionName
      Handler: index.handler
      Runtime: nodejs20.x
      Role: 
        !If
          - AddVpc
          - !GetAtt LambdaExecutionRoleWithVpc.Arn
          - !GetAtt LambdaExecutionRoleWithoutVpc.Arn
      Environment:
        Variables: 
          !If 
            - AddVpc
            - NEPTUNE_ENDPOINT: !Ref NeptuneEndpoint
            - Ref: "AWS::NoValue"
      VpcConfig: 
        !If 
          - AddVpc
          - SecurityGroupIds: 
              - !Ref LambdaExecutionSecurityGroup
            SubnetIds: !Ref SubnetIds
          - Ref: "AWS::NoValue"

  LambdaExecutionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: AddVpc
    Properties:
      GroupDescription: Enable Lambda access to Neptune
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Parameters:
  FunctionName:
    Type: String
  VpcId:
    Type: String
    Default: dummy-vpc-id
  SubnetIds:
    Type: CommaDelimitedList
    Default: dummy-subnet-id1,dummy-subnet-id2
  NeptuneEndpoint:
    Type: String
    Default: ""
  AddVpc:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: Whether to add VPC configuration to the Lambda function.
  CodeBucket:
    Type: String
  CodeKey:
    Type: String

Conditions:
  AddVpc: !Equals [!Ref AddVpc, "true"]
  NoVpc: !Not [!Condition AddVpc]

Outputs:
  LambdaFunctionName:
    Value: !Ref LambdaFunction
